heat_template_version: 2013-05-23

description: A load-balanced server

parameters:

  image:
    type: string
    description: Image used for servers

  key_name:
    type: string
    description: SSH key to connect to the servers

  key_save:
    type: string
    default: false

  flavor:
    type: string
    description: flavor used by the servers

  pool_id:
    type: string
    description: Pool to contact

  user_data:
    type: string
    description: Server user_data

  metadata:
    type: json

  public_network:
    type: string

  private_network:
    type: string

  private_subnet:
    type: string

  security_group:
    type: string


resources:

  server:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key_name }
      metadata: { get_param: metadata }
      user_data: { get_param: user_data }
      user_data_format: RAW
      networks:
        - port: { get_resource: server_port }

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network }
      fixed_ips:
        - subnet_id: { get_param: private_subnet }
      security_groups: [ { get_param: security_group } ]

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_network }
      port_id: { get_resource: server_port }

  lb_member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: { get_param: pool_id }
      address: { get_attr: [server, first_address] }
      protocol_port: 80

