heat_template_version: 2015-10-15

description: Nova flavor provider template

resources:

  flavor:
    type: OS::Nova::Flavor
    properties:
      disk: 1
      ram: 256
      vcpus: 1

outputs:
  flavor_id:
    description: Nova flavor ID
    value: {get_resource: flavor}
