heat_template_version: 2016-04-08
description: Load balanced Nova Server

parameters:
  image:
    type: string
  key_name:
    type: string
  flavor:
    type: string
  private_network:
    type: string
  private_subnet:
    type: string
  availability_zone:
    type: string
    default: nova
  flavor:
    type: string
    default: heat.tiny

resources:
  server:
    type: OS::Nova::Server
    properties:
      availability_zone: { get_param: availability_zone }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server_port }
    depends_on: server_port

  server_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_network }
      fixed_ips:
        - subnet_id: { get_param: private_subnet }

  volume:
    type: Test::Volume
    properties:
      nova_instance: {get_resource: server}
      availability_zone: { get_param: availability_zone }

outputs:
  instance_ip:
    value: { get_attr: [server, first_address] }
