heat_template_version: 2015-10-15

description: Nova KeyPair provider template

parameters:
  keypair_name:
    type: string
    default: keypair_heat

  save_key:
    type: string
    default: false

resources:

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name: {get_param: keypair_name}
      save_private_key: {get_param: save_key}
