heat_template_version: 2013-05-23

description: >
  Parent template for a simple environment.
  Heavy lifting done in nested stacks.

parameters:
  keypair_name:
    type: string
    default: heat_keypair

  image_name:
    type: string
    default: heat_cirros

resources:

  keypair:
    type: Test::KeyPair
    properties:
      keypair_name: {get_param: keypair_name}

  network:
    type: Test::Network

  glance_image:
    type: Test::GlanceImage
    properties:
      image_name: {get_param: image_name}

  flavor:
    type: Test::NovaFlavor

  server:
    type: Test::Server
    properties:
      image: {get_param: image_name}
      key_name: {get_param: keypair_name}
      flavor: {get_attr: [flavor, flavor_id]}
      private_network: {get_attr: [network, private_network_id]}
      private_subnet: {get_attr: [network, private_subnet_id]}
    depends_on: [network, glance_image, keypair, flavor]

